# server配置
server:
  port: 8080
  servlet:
    context-path: /api

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///user-center
      username: root
      password: 80234968
      driver-class-name: com.mysql.cj.jdbc.Driver
  #session 失效时间
  session:
    timeout: 86400

# mybatis-plus的配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 #已删除值
      logic-not-delete-value: 0


